const esc = text => String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const contexts = {
 'diwali-gifts':['Choose a festive combination','Compare the dry-fruit and chocolate selection first. The listed festive options add candles, diffusers or decorative idols at different price points. Check the individual contents list when choosing for family or friends.'],
 'corporate-diwali-gifts':['Plan a festive corporate order','Prepare separate employee and client counts, dietary preferences and the approved company message. Ask for a quotation covering the chosen hamper, branding and delivery destinations.'],
 'diwali-gifts-for-employees':['Make distribution easy','Confirm the team count and whether gifts go to one office or individual addresses. Agree the festive message and any alternatives before approving the packing list.'],
 'diwali-gifts-for-clients':['Choose a suitable client gift','Check the recipient’s gift policy and address. Keep the message personal and discuss discreet branding, especially when gifts are sent on behalf of an account team.'],
 'dry-fruit-hampers':['Compare jar counts and portions','Choose from two, three or four glass jars in a gift box. Ask for the exact assortment, net weight per jar, ingredient labels and shelf life; jar count alone does not tell you the portion size.'],
 'chocolate-hampers':['Choose chocolates that travel well','Share chocolate preferences and allergies, then confirm the actual assortment and shelf life. Ask about suitability for the destination and season before arranging delivery.'],
 'employee-welcome-kits':['Match the kit to the first day','Compare the Essential, Premium and Signature contents. Collect T-shirt sizes for the Signature kit and approve logo placement and any personalised welcome notes.'],
 'onboarding-kits':['Prepare the onboarding inserts','Measure any cards or printed inserts you want to include. Confirm which documents you supply, their quantity and the packing arrangement alongside your selected welcome kit.'],
 'corporate-merchandise':['Prepare artwork and sizes','Specify bottle or tumbler preferences, garment sizes and colour choices. Share your logo and ask for the suitable branding method, minimum quantity and sample arrangements for each item.'],
 'employee-gifts':['Choose for the work milestone','Match practical kits to new joiners and treat-filled boxes to team celebrations. Confirm individual names and any dietary requirements before requesting a quantity quote.'],
 'client-gifts':['Give with the relationship in mind','Compare desk gifts, dry-fruit boxes and celebration hampers. Share the occasion and recipient restrictions so the personal message and contents suit the relationship.'],
 'gourmet-hampers':['Plan the food pairing','Choose a coffee, tea or snack theme and confirm the exact brands, portions, allergens and shelf life. Made-to-order ideas need a quotation before an order can be agreed.'],
 'healthy-hampers':['Check the actual food labels','Choose according to the recipient’s preferences. Ask for ingredients, added-sugar information, portions and allergens rather than assuming that every option suits a particular diet.'],
 'wellness-hampers':['Make the contents personal','Share fragrance preferences and whether you want a journal, drink or candle. Ask about fragrance-free alternatives and confirm the final contents before ordering.']
};
function categoryGuide(c,items,shippingPaise) {
 const money=n=>'₹'+n.toLocaleString('en-IN');
 const [heading,advice]=contexts[c.slug] || (c.limit ? ['Plan the complete gift budget','Check whether each listing is a complete hamper or an individual supply. Add the container, contents and decorations before comparing the total with your budget.'] : ['Choose contents around the recipient','Compare the contents of each gift, then share the occasion, personal message and any recipient preferences with your enquiry.']);
 const priceText=items.length ? `Listed options in this collection range from ${money(Math.min(...items.map(p=>p.price)))} to ${money(Math.max(...items.map(p=>p.price)))}. See each product for its contents and current price. Customisation is quoted separately.` : 'These are made-to-order ideas. Share your preferred contents and budget so we can confirm an itemised quotation.';
 const examples=items.length?`<ul>${items.slice().sort((a,b)=>a.price-b.price).slice(0,3).map(p=>`<li><a href="../products/${p.slug}/">${esc(p.name)}</a> — ${money(p.price)}</li>`).join('')}</ul>`:'';
 return `<section class="wrap section category-buying-guide" aria-label="${esc(c.title)} ordering guide"><h2>${esc(heading)}</h2><p>${esc(advice)}</p><div class="shop-grid"><article><h3>Prices and contents</h3><p>${esc(priceText)}</p>${examples}</article><article><h3>Personalisation and quantities</h3><p>Send your preferred colours, message and any logo artwork with the required quantity. The minimum quantity depends on the product and branding method; ask us to confirm it in your quote. Quantity discounts are confirmed individually.</p></article><article><h3>Delivery and corporate orders</h3><p>Listed-product orders have a flat ${money(shippingPaise/100)} shipping fee per order. Custom and bulk delivery is confirmed in your quotation. Share the delivery postcode, number of addresses and required arrival date so we can check the schedule.</p></article></div><div class="faq"><details><summary>How soon can this order arrive?</summary><p>Contact us with your postcode, quantity and required date. We confirm production and delivery timing after checking stock and any personalisation; there is no fixed turnaround promised for every order.</p></details><details><summary>What do you need for a corporate quotation?</summary><p>Include your preferred products, recipient count, budget per gift, logo or message requirements and delivery locations. Ask for the final contents, total charges and delivery plan before confirming.</p></details><details><summary>Can I order online now?</summary><p>Online payment is being set up. You can save your choices in the basket after signing in, then contact us to confirm an order or request a customised quote.</p></details></div><a class="button secondary" href="../bulk-orders/?collection=${encodeURIComponent(c.title)}">Discuss this collection →</a></section>`;
}
module.exports={categoryGuide};
